---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense' 
summary: Descubra las novedades en Cloud Data Sense. 
---
= Novedades de Cloud Data Sense
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubra las novedades en Cloud Data Sense.



== 7 de marzo de 2023 (versión 1.21)



=== Nueva funcionalidad para agregar sus propias categorías personalizadas desde la interfaz de usuario de detección de datos

Data Sense le permite ahora agregar sus propias categorías personalizadas para que Data Sense identifique los archivos que se ajustan a esas categorías. La detección de datos tiene muchas https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-categories["categorías predefinidas"], por lo tanto, esta característica permite agregar categorías personalizadas para identificar dónde se encuentra la información que es única para la organización en los datos.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-categories["Leer más"^].



=== Ahora puede agregar palabras clave personalizadas desde la interfaz de usuario de detección de datos

Data Sense ha tenido la capacidad de agregar palabras clave personalizadas que Data Sense identificará durante un tiempo en exploraciones futuras. Sin embargo, necesitaba iniciar sesión en el host Linux de Data Sense y utilizar una interfaz de línea de comandos para agregar las palabras clave. En esta versión, la capacidad de agregar palabras clave personalizadas se encuentra en la interfaz de usuario de detección de datos, lo que facilita la adición y edición de estas palabras clave.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-keywords-from-a-list-of-words["Obtenga más información sobre cómo agregar palabras clave personalizadas desde la interfaz de usuario de Data Sense"^].



=== Capacidad de tener archivos de escaneado de detección de datos *no* cuando se cambie la "última hora de acceso"

De forma predeterminada, si Data Sense no tiene los permisos de "escritura" adecuados, el sistema no analizará los archivos de los volúmenes porque el sistema no puede revertir la "última hora de acceso" a la Marca de hora original. Sin embargo, si no le importa si la última hora de acceso se restablece a la hora original en los archivos, puede anular este comportamiento en la página Configuración para que detección de datos analice los volúmenes independientemente de los permisos.

Junto con esta capacidad, se ha agregado un nuevo filtro denominado "evento de análisis de análisis de análisis" para poder ver los archivos no clasificados porque la detección de datos no pudo revertir la hora a la que se accedió por última vez, o los archivos clasificados aunque la detección de datos no pudo revertir la hora a la que se accedió por última vez.

https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-collected-metadata.html#last-access-time-timestamp["Obtenga más información sobre la Marca de hora del último acceso y los permisos que requiere detección de datos"].



=== Se identifican tres nuevos tipos de datos personales por Data Sense

Data Sense puede identificar y categorizar archivos que contengan los siguientes tipos de datos:

* Número de tarjeta de identidad de Botswana (Omang)
* Número de pasaporte de Botswana
* Tarjeta de identidad de registro nacional de Singapur (NRIC)


https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data["Vea todos los tipos de datos personales que Data Sense puede identificar en sus datos"].



=== Funcionalidad actualizada para directorios

* La opción "Informe CSV claro" para Informes de investigación de datos ahora incluye información de los directorios.
* El filtro de tiempo "último acceso" muestra ahora la última hora a la que se accedió tanto para archivos como para directorios.




=== Mejoras en la instalación

* Data sense puede instalar en hosts Linux que ejecutan CentOS Stream 8.
* El instalador de detección de datos para sitios sin acceso a Internet (sitios oscuros) ahora realiza una comprobación previa para asegurarse de que el sistema y los requisitos de red están en su lugar para una instalación correcta.
* Los archivos de registro de auditoría de la instalación se guardan ahora y se escriben en `/ops/netapp/install_logs`.




== 5 de febrero de 2023 (versión 1.20)



=== Posibilidad de enviar correos electrónicos de notificación basados en políticas a cualquier dirección de correo electrónico

En versiones anteriores de Cloud Data Sense, puede enviar alertas de correo electrónico a los usuarios de BlueXP de su cuenta cuando ciertas políticas críticas devuelven resultados. Esta función le permite obtener notificaciones para proteger sus datos cuando no está en línea. Ahora también puede enviar alertas de correo electrónico desde Directivas a cualquier otro usuario - hasta 20 direcciones de correo electrónico - que no se encuentren en su cuenta de BlueXP.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-using-policies.html#sending-email-alerts-when-non-compliant-data-is-found["Obtenga más información sobre el envío de alertas por correo electrónico basadas en los resultados de la directiva"].



=== Ahora puede agregar patrones personales desde la interfaz de usuario de detección de datos

La detección de datos ha tenido la capacidad de agregar "datos personales" personalizados que la detección de datos identificará en futuros análisis durante un tiempo. Sin embargo, tenía que iniciar sesión en el host Linux de Data Sense y utilizar una línea de comandos para agregar los patrones personalizados. En esta versión, la capacidad de agregar patrones personales con un regex está en la interfaz de usuario de detección de datos, lo que hace muy fácil agregar y editar estos patrones personalizados.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-personal-data-identifiers-using-a-regex["Obtenga más información sobre cómo agregar patrones personalizados desde la interfaz de usuario de Data Sense"^].



=== Capacidad de mover 15 millones de archivos con Data Sense

Anteriormente, podría hacer que Data Sense trasladara un máximo de 100,000 archivos de origen a cualquier recurso compartido de NFS. Ahora puede mover hasta 15 millones de archivos a la vez. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Obtenga más información acerca de cómo mover archivos de origen con Data Sense"].



=== Capacidad para ver el número de usuarios que tienen acceso a archivos de SharePoint Online

El filtro "número de usuarios con acceso" ahora admite archivos almacenados en repositorios en línea de SharePoint. Anteriormente, solo se admitía los ficheros con recursos compartidos CIFS. Tenga en cuenta que los grupos de SharePoint que no están basados en directorios activos no se contarán en este filtro en este momento.



=== Se ha agregado un nuevo estado "éxito parcial" al panel Estado de acción

El nuevo estado "éxito parcial" indica que una acción de detección de datos ha finalizado y que algunos elementos han fallado y algunos elementos han tenido éxito, por ejemplo, al mover o eliminar archivos 100. Además, se ha cambiado el nombre del estado "terminado" por "correcto". En el pasado, el estado "terminado" podría incluir acciones que se han realizado correctamente y que han fallado. Ahora el estado "éxito" significa que todas las acciones se han realizado correctamente en todos los elementos. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-view-compliance-actions.html["Consulte cómo ver el panel Estado de acciones"].



== 9 de enero de 2023 (versión 1.19)



=== Capacidad para ver un gráfico de archivos que contienen datos confidenciales y que son excesivamente permisivos

El panel de control de gobierno ha agregado un área nueva _sensible Data y permisos amplios_ que proporciona un mapa térmico de archivos que contienen datos confidenciales (incluidos datos personales confidenciales y confidenciales) y que son demasiado permisivos. Esto puede ayudarle a ver dónde puede tener algunos riesgos con datos confidenciales. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-governance-data.html#data-listed-by-sensitivity-and-wide-permissions["Leer más"].



=== Hay tres filtros nuevos disponibles en la página Investigación de datos

Hay nuevos filtros disponibles para refinar los resultados que se muestran en la página Investigación de datos:

* El filtro "número de usuarios con acceso" muestra qué archivos y carpetas están abiertos a un determinado número de usuarios. Puede elegir un intervalo de números para refinar los resultados, por ejemplo, para ver los archivos a los que pueden acceder 51-100 usuarios.
* Los filtros "Hora de creación", "Hora descubierta", "última modificación" y "último acceso" ahora permiten crear un intervalo de fechas personalizado en lugar de sólo seleccionar un intervalo de días predefinido. Por ejemplo, puede buscar archivos con una "hora creada" "más de 6 meses" o con una fecha "última modificación" dentro de los "últimos 10 días".
* El filtro "Ruta de acceso" le permite especificar rutas que desea excluir de los resultados de la consulta filtrada. Si introduce rutas de acceso para incluir y excluir determinados datos, detección de datos busca primero todos los archivos en las rutas de acceso incluidas, quita los archivos de las rutas de acceso excluidas y, a continuación, muestra los resultados.


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-investigate-data.html#filtering-data-in-the-data-investigation-page["Consulte la lista de todos los filtros que puede utilizar para investigar los datos"].



=== El sentido de los datos puede identificar el número individual japonés

Data Sense puede identificar y categorizar archivos que contengan el número individual japonés (también conocido como Mi número). Esto incluye tanto el número personal como el número de mi corporativo. https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data["Vea todos los tipos de datos personales que Data Sense puede identificar en sus datos"].



== 11 de diciembre de 2022 (versión 1.18)



=== Mejoras en la instalación en las instalaciones

Se han agregado las siguientes mejoras para la instalación de detección de datos en las instalaciones:

* Ahora se comprueban algunos requisitos previos adicionales antes de que la instalación comience en un host local. Esto ayuda a asegurarse de que el sistema host esté preparado al 100 % para tener instalado el software Data Sense:
+
** comprobar si hay suficiente espacio en `/var/lib/docker`, `/tmp`, y. `/opt`
** pruebe los permisos pertinentes en todas las carpetas necesarias


* En la página Configuración, la sección entornos de trabajo muestra ahora _Working Environment ID_ y el _Scanner Group_ name. Necesitará conocer el identificador de entorno de trabajo si planea utilizar varios hosts de detección de datos para proporcionar potencia de procesamiento adicional para analizar sus fuentes de datos.
* También en la página Configuración, una nueva sección muestra los grupos de escáner que ha configurado y los nodos de escáner de cada grupo.


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html["Obtenga más información acerca de la instalación de Data Sense en un solo servidor host y en varios hosts"].



== 13 de noviembre de 2022 (versión 1.17)



=== Compatibilidad para analizar cuentas en las instalaciones de SharePoint

Ahora, el sentido de los datos puede analizar tanto cuentas en línea de SharePoint como cuentas en las instalaciones de SharePoint (SharePoint Server). Si necesita instalar SharePoint en sus propios servidores, o en sitios sin acceso a Internet, ahora puede hacer que Data Sense analice los archivos de usuario en esas cuentas. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-sharepoint.html#adding-a-sharepoint-on-premise-account["Leer más"^].



=== Capacidad para volver a analizar varios directorios (carpetas o recursos compartidos)

Ahora puede volver a analizar varios directorios (carpetas o recursos compartidos) inmediatamente para que los cambios se reflejen en el sistema. Esto le permite priorizar el reexamen de determinados datos antes de otros. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["Consulte cómo volver a analizar un directorio"^].



=== Posibilidad de añadir nodos de "escáner" locales adicionales para analizar orígenes de datos específicos

Si ha instalado Data Sense en una ubicación local y necesita más potencia de procesamiento de análisis para analizar determinados orígenes de datos, puede añadir más nodos de "escáner" y asignarles datos de origen. Puede añadir los nodos del escáner inmediatamente después de instalar el nodo Manager, o bien puede añadir un nodo de escáner más adelante.

Si es necesario, los nodos de escáner pueden instalarse en sistemas host que estén físicamente más cerca de los orígenes de datos que esté analizando. Cuanto más cerca esté el nodo del escáner de los datos, mejor será porque reduce la latencia de red tanto como sea posible mientras escanea datos. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html#add-scanner-nodes-to-an-existing-deployment["Consulte cómo instalar nodos de escáner para analizar orígenes de datos adicionales"^].



=== Los instaladores en las instalaciones ahora realizan una comprobación previa antes de iniciar la instalación

Al instalar Data Sense en un sistema Linux, el instalador comprueba si el sistema cumple todos los requisitos necesarios (CPU, RAM, capacidad, red, etc.) antes de iniciar la instalación real. Esto ayuda a detectar problemas *antes* usted pasa tiempo en la instalación.



== 6 de septiembre de 2022 (versión 1.16)



=== Capacidad de volver a analizar un repositorio inmediatamente para reflejar cambios en los archivos

Si necesita volver a analizar un repositorio determinado de inmediato para que los cambios se reflejen en el sistema, puede seleccionar el repositorio y volver a analizar dicho repositorio. Esto le permite priorizar el reexamen de determinados datos antes de otros. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["Consulte cómo volver a analizar un directorio"^].



=== Nuevo filtro para el estado del análisis de detección de datos en la página Investigación de datos

El filtro “Analysis Status” (Estado del análisis) permite enumerar los archivos que se encuentran en una etapa específica del análisis de detección de datos. Puede seleccionar una opción para mostrar la lista de archivos que están *primer escaneo pendiente*, *completado*, *Rescan pendiente* o que *ha fallado* para ser escaneados.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["Consulte la lista de todos los filtros que puede utilizar para investigar los datos"^].



=== Los sujetos de datos se consideran ahora parte de los "datos personales" encontrados en los escaneos

Data Sense ahora reconoce a los sujetos de datos como parte de los resultados personales que aparecen en el Panel de cumplimiento. Además, al realizar una búsqueda en la página de investigación, puede seleccionar "Temas de datos" en "datos personales" para ver sólo los archivos que contengan sujetos de datos.



=== Los archivos de rastro de detección de datos ahora se consideran parte de las "Categorías" que se encuentran en los análisis

El sensor de datos ahora reconoce los archivos de rastro como parte de las categorías que aparecen en la consola de cumplimiento de normativas. Son archivos que crea Data Sense al mover archivos de la ubicación de origen a un recurso compartido NFS. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Obtenga más información acerca de la forma en que se crean los archivos de rastro"^].

Además, al realizar una búsqueda en la página de investigación, puede seleccionar "Data Sense Breadmigbs" en "Category" (Categoría) para ver sólo los archivos de exploración de detección de datos.



== 7 de agosto de 2022 (versión 1.15)



=== Cinco nuevos tipos de datos personales de Nueva Zelanda se identifican por el sentido de los datos

Data Sense puede identificar y categorizar archivos que contengan los siguientes tipos de datos:

* Número de cuenta bancaria de Nueva Zelanda
* Número de Licencia de conducir de Nueva Zelanda
* Número IRD de Nueva Zelanda (ID fiscal)
* Número NHI (Índice Nacional de Salud) de Nueva Zelandia
* Número de pasaporte de Nueva Zelanda


link:reference-private-data-categories.html#types-of-personal-data["Vea todos los tipos de datos personales que Data Sense puede identificar en sus datos"].



=== Capacidad de añadir un archivo de rastro para indicar por qué se trasladó un archivo

Si utiliza la función Data Sense para mover archivos de origen a un recurso compartido de NFS, ahora puede dejar un archivo de rastro en la ubicación del archivo movido. Un archivo de rastro ayuda a los usuarios a comprender por qué se trasladó un archivo desde su ubicación original. Para cada archivo movido, el sistema crea un archivo de rastro en la ubicación de origen llamada `<filename>-breadcrumb-<date>.txt` para mostrar la ubicación en la que se ha movido el archivo y el usuario que lo ha movido. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Leer más"^].



=== Los datos personales y los datos personales confidenciales que se encuentran en sus directorios se muestran en los resultados de la investigación

La página Investigación de datos ahora muestra los resultados de datos personales y datos personales confidenciales que se encuentran en sus directorios (carpetas y recursos compartidos). https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-files-that-contain-personal-data["Vea un ejemplo aquí"^].



=== Ver el estado de cuántos volúmenes, bloques, etc. se han clasificado correctamente

Al ver los repositorios individuales que Data Sense está analizando (volúmenes, bloques, etc.), ahora puede ver cuántos se han "asignado" y cuántos se han "clasificado". La clasificación tarda más tiempo en realizarse la identificación de IA completa en todos los datos. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#viewing-the-scan-status-for-your-repositories["Vea cómo ver esta información"^].



=== Ahora puede agregar patrones personalizados que detección de datos identificará en sus datos

Hay dos formas de agregar "datos personales" personalizados que el sentido de datos identificará en futuras exploraciones. Esto le permite ver la imagen completa sobre dónde residen los datos potencialmente confidenciales en todos los archivos de su organización.

* Puede agregar palabras clave personalizadas desde un archivo de texto.
* Puede agregar un patrón personal utilizando una expresión regular (regex).


Estas palabras clave y patrones se agregan a los patrones predefinidos existentes que Data Sense ya utiliza, y los resultados serán visibles en la sección patrones personales. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html["Leer más"^].



== 6 de julio de 2022 (versión 1.14)



=== Ahora puede ver los usuarios y grupos que tienen acceso a sus directorios

Anteriormente, podría ver los tipos de permisos abiertos concedidos en archivos individuales. Ahora puede ver una lista de todos los usuarios o grupos que tienen acceso a directorios (carpetas y recursos compartidos de archivos) y los tipos de permisos que tienen. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-permissions-for-files-and-directories["Vea cómo ver los usuarios y grupos que tienen acceso a las carpetas y los recursos compartidos de archivos"].



=== Puede "pausar" el análisis de un repositorio para detener temporalmente el análisis de cierto contenido

Pausar el análisis significa que Data Sense no realizará más análisis futuro de adiciones o cambios en un volumen o bloque, pero que todavía estarán disponibles en el sistema todos los resultados actuales. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#pausing-and-resuming-scanning-for-a-repository["Consulte cómo pausar y reanudar la exploración"].



=== Los datos DE licencias de conducir DE EE.UU. Procedentes de tres estados adicionales pueden ser identificados por Data Sense

El sentido de los datos puede identificar y categorizar archivos que contengan datos de licencias de conducir de Indiana, Nueva York y Texas. link:reference-private-data-categories.html#types-of-personal-data["Vea todos los tipos de datos personales que Data Sense puede identificar en sus datos"].



=== Las directivas devuelven ahora directorios que coinciden con los criterios de búsqueda

En el pasado, cuando se creó una directiva personalizada, los resultados mostraban los archivos que coincidieron con los criterios de búsqueda. Ahora los resultados también muestran los directorios (carpetas y archivos compartidos) que coinciden con la consulta. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-org-private-data.html#creating-custom-policies["Más información acerca de la creación de políticas"].



=== Data sense puede transferir hasta 100,000 archivos cada vez

Si planea utilizar Data Sense para mover archivos de un origen de datos escaneado a un recurso compartido NFS, el número máximo de archivos se ha aumentado a 100,000. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["Vea cómo mover archivos con Data Sense"].



== 12 de junio de 2022 (versión 1.13.1)



=== Ahora puede descargar los resultados desde la página Investigación de datos como un informe .JSON

Después de filtrar los datos en la página Investigación de datos, ahora puede guardar los datos como un informe en un archivo .JSON que puede exportar a un recurso compartido NFS, además de guardar los datos en un archivo .CSV en el sistema local. Asegúrese de que Data Sense tiene los permisos correctos para el acceso de exportación. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-generating-compliance-reports.html#data-investigation-report["Consulte cómo crear informes desde la página Investigación de datos"].



=== Capacidad para desinstalar Data Sense de la interfaz de usuario de Data Sense

Puede desinstalar Data Sense para eliminar de forma permanente el software del host y, en el caso de una implementación de cloud, eliminar la máquina virtual/instancia en la que se ha implementado Data Sense. Al eliminar la instancia, se elimina permanentemente toda la información indexada que se ha analizado Data Sense. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-uninstall-data-sense.html["Descubra cómo"].



=== El registro de auditoría está ahora disponible para realizar el seguimiento del historial de acciones que ha realizado la detección de datos

El registro de auditoría realiza un seguimiento de las actividades de administración que Data Sense ha realizado en archivos de todos los entornos de trabajo y orígenes de datos que Data Sense está analizando. Las actividades pueden ser generadas por el usuario (eliminar un archivo, crear una directiva, etc.) o generadas por una directiva (agregar etiquetas automáticamente a los archivos, eliminar archivos automáticamente, etc.).

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-audit-data-sense-actions.html["Consulte más detalles sobre el registro de auditoría"].



=== Nuevo filtro para el número de identificadores confidenciales en la página Investigación de datos

El filtro “número de identificadores” permite enumerar los archivos que tienen un cierto número de identificadores confidenciales, incluidos datos personales y datos personales confidenciales. Puede seleccionar un rango como 1-10 o 501-1000 para ver sólo los archivos que contienen ese número de identificadores confidenciales.

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["Consulte la lista de todos los filtros que puede utilizar para investigar los datos"].



=== Ahora puede editar las directivas existentes que ha creado

Si necesita realizar un cambio en una directiva personalizada que ha creado anteriormente, ahora puede editar la directiva en lugar de crear una nueva. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-org-private-data.html#editing-policies["Vea cómo editar una directiva"].



== 11 de mayo de 2022 (versión 1.12.1)



=== Se ha agregado compatibilidad para analizar datos en cuentas de Google Drive

Ahora puede agregar sus cuentas de Google Drive a Data Sense para poder escanear los documentos y archivos de esas cuentas de Google Drive. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-google-drive.html["Descubra cómo analizar sus cuentas de Google Drive"].

El sentido de los datos puede identificar la Información personal identificable (PII) en los siguientes tipos de archivos de Google desde la suite Google Docs -- Docs, Sheets, and Slides -- además de la https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-files["tipos de archivo existentes"].



=== Vista de nivel de directorio agregada a la página Investigación de datos

Además de ver y filtrar datos de todos los archivos y bases de datos, ahora puede ver y filtrar datos en función de todos los datos de carpetas y recursos compartidos de la página Investigación de datos. Los directorios se indexarán para recursos compartidos CIFS y NFS analizados, así como para carpetas de OneDrive, SharePoint y Google Drive. Ahora puede ver los permisos y gestionar los datos en el nivel de directorio. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["Vea cómo seleccionar la vista directorios de los datos escaneados"].



=== Expanda grupos para mostrar los usuarios o miembros que tienen permisos para tener acceso a un archivo

Como parte de las capacidades de permisos de detección de datos, ahora puede ver la lista de usuarios y grupos que tienen acceso a un archivo. Cada grupo se puede expandir para mostrar la lista de usuarios del grupo. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-permissions-for-files["Vea cómo ver usuarios y grupos que tienen permisos de lectura y/o escritura en sus archivos"].



=== Se han agregado dos nuevos filtros a la página Investigación de datos

* El filtro “Tipo de directorio” permite afinar los datos para ver sólo carpetas o recursos compartidos. Los resultados se mostrarán en la nueva pestaña *directorios*.
* El filtro "permisos de usuario/grupo" le permite enumerar los archivos, carpetas y recursos compartidos a los que un usuario o grupo específico tiene permisos de lectura y/o escritura. Puede seleccionar varios usuarios y/o nombres de grupo - o introducir un nombre parcial.


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["Consulte la lista de todos los filtros que puede utilizar para investigar los datos"].



== 5 de abril de 2022 (versión 1.11.1)



=== Cuatro nuevos tipos de datos personales australianos se pueden identificar mediante detección de datos

Data Sense puede identificar y categorizar archivos que contengan el TFN (número de archivo fiscal) australiano, el número de licencia de conducir australiano, el número de Medicare australiano y el número de pasaporte australiano. link:reference-private-data-categories.html#types-of-personal-data["Vea todos los tipos de datos personales que Data Sense puede identificar en sus datos"].



=== El servidor de Active Directory global puede ser ahora un servidor LDAP

El servidor global de Active Directory que se integra con Data Sense puede ser ahora un servidor LDAP además del servidor DNS previamente admitido. link:task-add-active-directory-datasense.html["Vaya aquí para obtener más información"].



== 15 de marzo de 2022 (versión 1.10.0)



=== Nuevo filtro para mostrar los archivos a los que un usuario o grupo específico tiene permisos de lectura o escritura

Se ha agregado un nuevo filtro denominado "permisos de usuario/grupo" para que pueda enumerar los archivos a los que un usuario o grupo específico tiene permisos de lectura y/o escritura. Puede seleccionar uno o más nombres de usuario o de grupo, o bien introducir un nombre parcial. Esta funcionalidad está disponible para volúmenes en Cloud Volumes ONTAP, ONTAP en las instalaciones, Azure NetApp Files, Amazon FSX para ONTAP y recursos compartidos de archivos.



=== El sentido de los datos puede determinar los permisos para los archivos en cuentas de SharePoint y OneDrive

Data Sense puede leer los permisos existentes para los archivos que se están analizando en cuentas de OneDrive y cuentas de SharePoint ahora. Esta información aparece en los detalles del panel de investigación de los archivos y en el área permisos abiertos del Panel de control de gobierno.



=== Dos tipos adicionales de datos personales pueden ser identificados por Data Sense

* INSEE Francés - el código INSEE es un código numérico utilizado por el Instituto Nacional de Estadística y Estudios Económicos de Francia (INSEE) para identificar diversas entidades.
* Contraseñas: Esta información se identifica mediante la validación de proximidad buscando permutaciones de la palabra "password" junto a una cadena alfanumérica. El número de elementos encontrados se enumerará en "resultados personales" en el Panel de cumplimiento. Puede buscar archivos que contengan contraseñas en el panel Investigación mediante el filtro * datos personales > Contraseña*.




=== Compatibilidad con el análisis de datos de OneDrive y SharePoint cuando se implementa en un sitio oscuro

Cuando ha puesto en marcha Cloud Data Sense en un host en una ubicación en las instalaciones que no tiene acceso a Internet, ahora puede analizar datos locales de cuentas de OneDrive o de SharePoint. link:task-deploy-compliance-dark-site.html#sharepoint-and-onedrive-special-requirements["Deberá permitir el acceso a los siguientes puntos finales."]



=== La capacidad Beta para usar Cloud Data Sense para analizar sus archivos de Cloud Backup se ha interrumpido en esta versión



== 9 de febrero de 2022



=== Se ha agregado compatibilidad para analizar cuentas en línea de Microsoft SharePoint

Ahora puede agregar sus cuentas en línea de SharePoint a Data Sense para poder analizar los documentos y archivos de sus sitios de SharePoint. link:task-scanning-sharepoint.html["Vea cómo analizar sus cuentas de SharePoint"].



=== Data Sense puede copiar archivos de un origen de datos a una ubicación de destino y sincronizar dichos archivos

Esto es útil para situaciones en las que se están migrando datos y se desea detectar los últimos cambios que se están realizando en los archivos. Esta acción utiliza https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["Cloud Sync de NetApp"^] funcionalidad para copiar y sincronizar datos de un origen en un destino.

link:task-managing-highlights.html#copying-and-synchronizing-source-files-to-a-target-system["Vea cómo copiar y sincronizar archivos"].



=== Nueva compatibilidad de idiomas para los informes DSAR

Ahora se admiten alemán y español cuando se buscan nombres de sujetos de datos para crear informes de solicitud de acceso a sujetos de datos (DSAR). Este informe está diseñado para ayudar en el requisito de su organización a cumplir con el RGPD o con leyes de privacidad de datos similares.



=== Se pueden identificar tres tipos adicionales de datos personales mediante Data Sense

Data Sense ahora puede encontrar números franceses de seguridad social, ID franceses y números de licencia de controlador francés en archivos. link:reference-private-data-categories.html#types-of-personal-data["Consulte la lista de todos los tipos de datos personales que detección de datos identifica en los análisis"].



=== Se ha cambiado el puerto del grupo de seguridad para la comunicación de detección de datos con el conector

El grupo de seguridad de Cloud Manager Connector utilizará el puerto 443 en lugar del puerto 80 para el tráfico entrante y saliente hacia y desde la instancia de detección de datos para mayor seguridad. Ambos puertos permanecen abiertos en este momento, por lo que no debería ver ningún problema, pero debería actualizar el grupo de seguridad en cualquier despliegue anterior del conector como el puerto 80 quedará obsoleto en una versión futura.



== 2 de enero de 2022



=== Capacidad de integrar un Active Directory global para identificar los propietarios de archivos y permisos

Ahora puede integrar un Active Directory global con Cloud Data Sense para mejorar los resultados que los informes de Data Sense sobre los propietarios de los archivos y qué usuarios y grupos tienen acceso a los archivos.

Además de las credenciales de Active Directory que introduzca para que Data Sense pueda analizar volúmenes de CIFS desde ciertos orígenes de datos, esta nueva integración ofrece como integración adicional para otros usuarios y sistemas. Data sense buscará en todos los directorios activos integrados para los detalles de permisos y usuarios. link:task-add-active-directory-datasense.html["Descubra cómo configurar su Active Directory global"].



=== Las "políticas" de detección de datos ahora se pueden utilizar para eliminar archivos

Data Sense puede eliminar automáticamente los archivos que coinciden con la consulta definida en una directiva. link:task-managing-highlights.html#deleting-source-files-automatically-using-policies["Vea cómo crear directivas personalizadas"].
